[biome]
has_sugi_forest = false
has_windswept_sugi_forest = true
has_blooming_sugi_forest = false
has_lavender_fields = false
has_marsh = false
has_bamboo_wetlands = false
has_wisteria_forest = false
has_redwood_forest = false
has_snowy_redwood_forest = false
has_aspen_forest = false
has_maple_woodlands = false
has_golden_wilds = false
has_marigold_meadows = false
has_fir_forest = false
has_snowy_fir_forest = false
has_cypress_fields = false
has_cedar_thicket = false
has_carnation_fields = false
has_stratified_desert = false
has_blooming_dunes = false
has_lively_dunes = false
has_drylands = false
has_wooded_drylands = false
has_xeric_plains = false
has_white_cliffs = false
has_prairie = false
has_oak_savanna = false
has_heather_fields = false
has_tundra = false
has_alpine_clearings = true
has_alpine_highlands = false
has_coniferous_covert = false
has_boreal_taiga = false
has_tropical_shores = false
has_tropical_woods = false
has_sparse_tropical_woods = false
has_tropical_basin = false
has_arid_savanna = false
has_scorched_dunes = false
has_flowering_shrubland = false
has_shrubland = false
has_arid_highlands = false
has_shrubby_highlands = false
has_woody_highlands = false
has_red_peaks = false
has_dusty_slopes = false
has_snowcapped_red_peaks = false
has_sleeted_slopes = false
has_blooming_highlands = false
has_chaparral = false
has_floral_ridges = true
